template: 'facelessuser:master-labels:labels.yml:master'

# Wildcard labels

brace_expansion: true
extended_glob: true

rules:
  - labels: [infrastructure]
    patterns: ['*|-@(*.md|*.py|*.sublime-@(keymap|menu|settings|commands))', '.github/**']

  - labels: [source]
    patterns: ['**/*.py|-tests']

  - labels: [docs]
    patterns: ['**/*.md|docs/**']

  - labels: [tests]
    patterns: ['tests/**']

  - labels: [export-html]
    patterns: ['ExportHtml.py']

  - labels: [html-assets]
    patterns: ['@(js|css)/**']

  - labels: [color-schemes]
    patterns: ['ColorSchemes/**']

  - labels: [icons]
    patterns: ['icons/**']

  - labels: [export-bbcode]
    patterns: ['ExportBbcode.py']

  - labels: [scheme-handling]
    patterns: ['lib/color_scheme*.py|lib/rgba.py|lib/x11colors.py']

  - labels: [notify]
    patterns: ['lib/notify.py']

  - labels: [browser]
    patterns: ['lib/browsers.py']

  - labels: [settings]
    patterns: ['*.sublime-@(keymap|menu|settings|commands)']

# Label management

labels:
- name: export-html
  color: subcategory
  description: Related to HTML exporting.

- name: export-bbcode
  color: subcategory
  description: Related to BBCode exporting.

- name: scheme-handling
  color: subcategory
  description: Related to scheme handling.

- name: notify
  color: subcategory
  description: Related to notifications.

- name: browser
  color: subcategory
  description: Related to browser handling.

- name: html-assets
  color: subcategory
  description: Related to HTML assets.

- name: color-schemes
  color: subcategory
  description: Related to provided color schemes.

- name: icons
  color: subcategory
  description: Related to icons.

- name: settings
  color: subcategory
  description: Related to Sublime settings.
